/**
 * @file gcpetchattype.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum ePetChatType
 */
enum ePetChatType : uint32_t
{
    EPetChatType_Adopted = 0,
    EPetChatType_Hatched = 1,
    EPetChatType_Summoned = 2,
    EPetChatType_Greeting = 3,
    EPetChatType_Hazard = 4,
    EPetChatType_Scanning = 5,
    EPetChatType_PositiveEmote = 6,
    EPetChatType_HungryEmote = 7,
    EPetChatType_LonelyEmote = 8,
    EPetChatType_Go_There = 9,
    EPetChatType_Come_Here = 10,
    EPetChatType_Planet = 11,
    EPetChatType_Mine = 12,
    EPetChatType_Attack = 13,
    EPetChatType_Chase = 14,
    EPetChatType_ReceivedTreat = 15,
    EPetChatType_Tickled = 16,
    EPetChatType_Ride = 17,
    EPetChatType_Egg_Laid = 18,
    EPetChatType_Customise = 19,
    EPetChatType_Unsummoned = 20,
};

/**
 * @class cGcPetChatType
 */
class cGcPetChatType : cTkMetaData::Registrar<cGcPetChatType>, cTkMetaDataXML::Registrar<cGcPetChatType>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x51175DF2E4A2F863,
    };
    enum
    {
        mu64TemplateHash = 0x12CAC40DB6314D79,
    };

    ePetChatType PetChatType;
};

SKYSCRAPER_END
