/**
 * @file gcstatusmessagedefinition.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <gamestate/messages/gcstatusmessagemissionmarkup.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eReplicateTo
 */
enum eReplicateTo : uint32_t
{
    EReplicateTo_None = 0,
    EReplicateTo_Fireteam = 1,
    EReplicateTo_Fireteam_SameUA = 2,
    EReplicateTo_Global = 3,
    EReplicateTo_Global_Distance = 4,
    EReplicateTo_Fireteam_Distance = 5,
    EReplicateTo_Fireteam_Global_Distance = 6,
    EReplicateTo_Not_Fireteam = 7,
};

/**
 * @class cGcStatusMessageDefinition
 */
class cGcStatusMessageDefinition : cTkMetaData::Registrar<cGcStatusMessageDefinition>, cTkMetaDataXML::Registrar<cGcStatusMessageDefinition>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x93C1244DBEE0E0CF,
    };
    enum
    {
        mu64TemplateHash = 0xDE28BA6FB5EB5CDE,
    };

    TkID<128> mId;
    TkID<256> mMessage;
    bool mbAddPlayerNamePrefix;
    bool mbAddPetNamePrefix;
    bool mbAddFriendlyDronePrefix;
    bool mbIncludePlayerName;
    eReplicateTo ReplicateTo;
    bool mbPostLocally;
    float mfDistance;
    float mfDisplayDurationMultiplier;
    bool mbOnlyInMultiplayer;
    bool mbOnlyOnFireteam;
    cGcStatusMessageMissionMarkup MissionMarkup;
};

SKYSCRAPER_END
