/**
 * @file gccreaturedata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/ecosystem/creatures/gccreaturetypes.meta.h>
#include <simulation/ecosystem/creatures/gccreaturetagandrarity.meta.h>
#include <reality/gccreaturerarity.meta.h>
#include <simulation/ecosystem/creatures/gccreaturerolefrequencymodifier.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eMoveArea
 */
enum eMoveArea : uint32_t
{
    EMoveArea_Ground = 0,
    EMoveArea_Water = 1,
    EMoveArea_Air = 2,
    EMoveArea_Space = 3,
};

/**
 * @class cGcCreatureData
 */
class cGcCreatureData : cTkMetaData::Registrar<cGcCreatureData>, cTkMetaDataXML::Registrar<cGcCreatureData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x132EB7906E53B7A7,
    };
    enum
    {
        mu64TemplateHash = 0xE8545DE962F52F8E,
    };

    TkID<128> mId;
    bool mbOnlySpawnWhenIdIsForced;
    cGcCreatureTypes ForceType;
    cGcCreatureTypes RealType;
    bool mbEcoSystemCreature;
    bool mbCanBeFemale;
    cTkDynamicArray<cGcCreatureTagAndRarity> maTags;
    eMoveArea MoveArea;
    float mfMinScale;
    float mfMaxScale;
    float mfFurLengthModifierAtMinScale;
    float mfFurLengthModifierAtMaxScale;
    float mfFurChance;
    cGcCreatureRarity Rarity;
    cGcCreatureRoleFrequencyModifier PredatorProbabilityModifier;
    cGcCreatureRoleFrequencyModifier HerbivoreProbabilityModifier;
    cTkDynamicArray<cTkClassPointer> maData;
};

SKYSCRAPER_END
