/**
 * @file gcpetbehaviourmoodmodifier.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/ecosystem/creatures/data/gccreaturepetmood.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcPetBehaviourMoodModifier
 */
class cGcPetBehaviourMoodModifier : cTkMetaData::Registrar<cGcPetBehaviourMoodModifier>, cTkMetaDataXML::Registrar<cGcPetBehaviourMoodModifier>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x7665E5534F420118,
    };
    enum
    {
        mu64TemplateHash = 0x8D3E77D7F2B1C8B2,
    };

    cGcCreaturePetMood Mood;
    float mfMoodMin;
    float mfMoodMax;
    float mfWeightModifierMin;
    float mfWeightModifierMax;
    float mfCooldownModifierMin;
    float mfCooldownModifierMax;
};

SKYSCRAPER_END
