/**
 * @file gcmissionsequencedetailmessagepoint.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum ePointState
 */
enum ePointState : uint32_t
{
    EPointState_Statement = 0,
    EPointState_ObjectiveIncomplete = 1,
    EPointState_ObjectiveComplete = 2,
};

/**
 * @class cGcMissionSequenceDetailMessagePoint
 */
class cGcMissionSequenceDetailMessagePoint : cTkMetaData::Registrar<cGcMissionSequenceDetailMessagePoint>, cTkMetaDataXML::Registrar<cGcMissionSequenceDetailMessagePoint>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xC2F4FABD9EDAFE6A,
    };
    enum
    {
        mu64TemplateHash = 0x111193B7216264B4,
    };

    TkID<256> mText;
    ePointState PointState;
    TkID<128> mInsertItemName;
};

SKYSCRAPER_END
