/**
 * @file gcdoshipescort.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/spaceship/ai/gcaispaceshiproles.meta.h>
#include <reality/gcrealitycommonfactions.meta.h>
#include <simulation/spaceship/ai/gcaispaceshiptypes.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcDoShipEscort
 */
class cGcDoShipEscort : cTkMetaData::Registrar<cGcDoShipEscort>, cTkMetaDataXML::Registrar<cGcDoShipEscort>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x68C0F45A086C1EB,
    };
    enum
    {
        mu64TemplateHash = 0x122643798D35042D,
    };

    bool mbMatchRole;
    cGcAISpaceshipRoles EscortTargetShipRole;
    bool mbMatchFaction;
    cGcRealityCommonFactions EscortTargetShipFaction;
    bool mbMatchType;
    cGcAISpaceshipTypes EscortTargetShipType;
    float mfMaxSearchDistance;
};

SKYSCRAPER_END
