/**
 * @file gcbasebuildingentry.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <gamestate/basebuilding/gcbasebuildingpartstyle.meta.h>
#include <toolkit/tkmodelresource.meta.h>
#include <gamestate/basebuilding/gcbasebuildingobjectdecorationtypes.meta.h>
#include <simulation/solarsystem/planet/gcbiometype.meta.h>
#include <gamestate/basebuilding/gcbasebuildingentrygroup.meta.h>
#include <gamestate/basebuilding/gcbaselinkgriddata.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eBaseTerrainEditShape
 */
enum eBaseTerrainEditShape : uint32_t
{
    EBaseTerrainEditShape_Cube = 0,
    EBaseTerrainEditShape_Cylinder = 1,
};

/**
 * @class cGcBaseBuildingEntry
 */
class cGcBaseBuildingEntry : cTkMetaData::Registrar<cGcBaseBuildingEntry>, cTkMetaDataXML::Registrar<cGcBaseBuildingEntry>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xA6F7B710166F6076,
    };
    enum
    {
        mu64TemplateHash = 0x2E18738D74B90B8C,
    };

    TkID<128> mID;
    bool mbIsTemporary;
    bool mbIsFromModFolder;
    cGcBaseBuildingPartStyle Style;
    cTkModelResource PlacementScene;
    cGcBaseBuildingObjectDecorationTypes DecorationType;
    bool mbIsPlaceable;
    bool mbIsDecoration;
    cGcBiomeType Biome;
    bool mbBuildableOnPlanetBase;
    bool mbBuildableOnSpaceBase;
    bool mbBuildableOnFreighter;
    bool mbBuildableOnPlanet;
    bool mbBuildableOnPlanetWithProduct;
    bool mbBuildableUnderwater;
    bool mbBuildableAboveWater;
    int miPlanetLimit;
    int miRegionLimit;
    int miPlanetBaseLimit;
    int miFreighterBaseLimit;
    bool mbCheckPlaceholderCollision;
    bool mbCheckPlayerCollision;
    bool mbCanRotate3D;
    bool mbCanScale;
    cTkDynamicArray<cGcBaseBuildingEntryGroup> maGroups;
    int miStorageContainerIndex;
    TkID<256> mColourPaletteGroupId;
    TkID<256> mDefaultColourPaletteId;
    TkID<256> mMaterialGroupId;
    TkID<256> mDefaultMaterialId;
    bool mbCanChangeColour;
    bool mbCanChangeMaterial;
    bool mbCanPickUp;
    bool mbShowInBuildMenu;
    cTkDynamicArray<TkID<128>> maCompositePartObjectIDs;
    cTkDynamicArray<TkID<128>> maFamilyIDs;
    float mfBuildEffectAccelerator;
    bool mbRemovesAttachedDecoration;
    bool mbRemovesWhenUnsnapped;
    bool mbEditsTerrain;
    eBaseTerrainEditShape BaseTerrainEditShape;
    float mfMinimumDeleteDistance;
    bool mbIsSealed;
    bool mbCloseMenuAfterBuild;
    cGcBaseLinkGridData LinkGridData;
    int miGhostsCountOverride;
    bool mbShowGhosts;
    float mfSnappingDistanceOverride;
    int miRegionSpawnLOD;
    cTkModelResource NPCInteractionScene;
};

SKYSCRAPER_END
