/**
 * @file gcbasebuildingpartdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <gamestate/basebuilding/gcbasebuildingpartstyle.meta.h>
#include <toolkit/utilities/data/tkmagicmodeldata.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcBaseBuildingPartData
 */
class cGcBaseBuildingPartData
{
  public:
    enum
    {
        ClassNameHash = 0x4F6F7504AD1EBFFC,
    };

    union
    {
        struct
        {
            TkID<256> mPartID;
            cGcBaseBuildingPartStyle Style;
            cTkMagicModelData MagicData;
            unsigned int muiNodesCost;
            unsigned int muiTimeCost;
            unsigned int muiPhysicsCost;
            unsigned int muiMeshesCost;
            unsigned int muiInstanceNodesCost;
            unsigned int muiInstanceTimeCost;
            unsigned int muiInstanceMeshesCost;
            unsigned long long mui64LastProfiledTimestamp;
            unsigned long long mui64InstanceLastProfiledTimestamp;
        };
    };
};

SKYSCRAPER_END
