/**
 * @file gcinteractionbuffertype.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eInteractionBufferType
 */
enum eInteractionBufferType : uint32_t
{
    EInteractionBufferType_Distress_Signal = 0,
    EInteractionBufferType_Crate = 1,
    EInteractionBufferType_Destructable = 2,
    EInteractionBufferType_Terrain = 3,
    EInteractionBufferType_Cost = 4,
    EInteractionBufferType_Building = 5,
    EInteractionBufferType_Creature = 6,
    EInteractionBufferType_Maintenance = 7,
    EInteractionBufferType_Personal = 8,
    EInteractionBufferType_Personal_Maintenance = 9,
    EInteractionBufferType_FireteamSync = 10,
};

/**
 * @class cGcInteractionBufferType
 */
class cGcInteractionBufferType
{
  public:
    enum
    {
        ClassNameHash = 0x56096224708D16B,
    };

    union
    {
        struct
        {
            eInteractionBufferType InteractionBufferType;
        };
    };
};

SKYSCRAPER_END
