/**
 * @file gcgalaxygenerationsetupdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcGalaxyGenerationSetupData
 */
class cGcGalaxyGenerationSetupData
{
  public:
    enum
    {
        ClassNameHash = 0x74E6E445263E30C1,
    };

    union
    {
        struct
        {
            float mfSpiralFormChance;
            cTkVector2 mSpiralInclusion;
            cTkVector2 mSpiralFlex;
            float mfSpiralTwistMult;
            cTkVector3 mSpiralPull;
            cTkVector2 mSpiralSizeScale;
            float mfRareSunChance;
            cTkVector2 mConnectionAttractorMax;
            cTkVector2 mConnectionAttractorMin;
            cTkVector2 mConnectionDistortion;
            float mfConnectionDistortionTMult;
            float mfConnectionDistanceLimit;
            cTkVector2 mBaseSize;
            cTkFixedArray<cTkVector2, 4> maStarSize;
            float mfBaseTurbulenceScale;
            float mfBaseTurbulenceLac;
            float mfBaseTurbulenceGain;
            float mfBaseGenerationThreshold;
            float mfFieldGenerationThreshold;
            float mfStarGenerationThreshold;
            cTkVector4 mInnerFieldScales;
            float mfSizeNoiseScale;
            float mfSizeNoisePower;
            float mfSizeField4Inf;
            float mfFieldAlphaBase;
            float mfFieldAlphaField1Inf;
            float mfFieldAlphaField2SqInf;
            float mfStarHighlightChance;
            cTkVector2 mStarHighlightAlpha;
            cTkVector2 mStarHighlightSize;
            float mfColourBaseBlendOnSize;
            cTkFixedArray<cTkColour, 10> maInnerSectorColours;
        };
    };
};

SKYSCRAPER_END
