/**
 * @file gcprojectileimpacttype.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eImpact
 */
enum eImpact : uint32_t
{
    EImpact_Default = 0,
    EImpact_Terrain = 1,
    EImpact_Substance = 2,
    EImpact_Rock = 3,
    EImpact_Asteroid = 4,
    EImpact_Shield = 5,
    EImpact_Creature = 6,
    EImpact_Robot = 7,
    EImpact_Freighter = 8,
    EImpact_Cargo = 9,
    EImpact_Ship = 10,
    EImpact_Plant = 11,
    EImpact_NeedsTech = 12,
    EImpact_Player = 13,
    EImpact_OtherPlayer = 14,
    EImpact_SentinelShield = 15,
    EImpact_SpaceshipShield = 16,
};

/**
 * @class cGcProjectileImpactType
 */
class cGcProjectileImpactType : cTkMetaData::Registrar<cGcProjectileImpactType>, cTkMetaDataXML::Registrar<cGcProjectileImpactType>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xC652A220FFABA4FE,
    };
    enum
    {
        mu64TemplateHash = 0x4B2046067B91DF22,
    };

    eImpact Impact;
};

SKYSCRAPER_END
