/**
 * @file gcaishipspawnmarkerdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <toolkit/tktextureresource.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eShipsToMark
 */
enum eShipsToMark : uint32_t
{
    EShipsToMark_None = 0,
    EShipsToMark_Leader = 1,
    EShipsToMark_All = 2,
};

/**
 * @class cGcAIShipSpawnMarkerData
 */
class cGcAIShipSpawnMarkerData : cTkMetaData::Registrar<cGcAIShipSpawnMarkerData>, cTkMetaDataXML::Registrar<cGcAIShipSpawnMarkerData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xDB40771B3EB38336,
    };
    enum
    {
        mu64TemplateHash = 0x103B4E1E1547DE0E,
    };

    cTkTextureResource MarkerIcon;
    TkID<256> mMarkerLabel;
    bool mbHideDuringCombat;
    float mfMinVisibleRange;
    float mfMaxVisibleRange;
    float mfMinAngleVisible;
    eShipsToMark ShipsToMark;
};

SKYSCRAPER_END
