/**
 * @file gcbytebeattoken.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eByteBeatToken
 */
enum eByteBeatToken : uint32_t
{
    EByteBeatToken_T = 0,
    EByteBeatToken_AND = 1,
    EByteBeatToken_OR = 2,
    EByteBeatToken_XOR = 3,
    EByteBeatToken_Plus = 4,
    EByteBeatToken_Minus = 5,
    EByteBeatToken_Multiply = 6,
    EByteBeatToken_Divide = 7,
    EByteBeatToken_Modulo = 8,
    EByteBeatToken_ShiftLeft = 9,
    EByteBeatToken_ShiftRight = 10,
    EByteBeatToken_Greater = 11,
    EByteBeatToken_GreaterEqual = 12,
    EByteBeatToken_Less = 13,
    EByteBeatToken_LessEqual = 14,
    EByteBeatToken_Number = 15,
    EByteBeatToken_OpenParenthesis = 16,
    EByteBeatToken_CloseParenthesis = 17,
};

/**
 * @class cGcByteBeatToken
 */
class cGcByteBeatToken
{
  public:
    enum
    {
        ClassNameHash = 0x1FC756C2E641CC49,
    };

    union
    {
        struct
        {
            eByteBeatToken ByteBeatToken;
        };
    };
};

SKYSCRAPER_END
