/**
 * @file tkproceduraltexture.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <toolkit/tkpalettetexture.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eTextureGameplayUse
 */
enum eTextureGameplayUse : uint32_t
{
    ETextureGameplayUse_IgnoreName = 0,
    ETextureGameplayUse_MatchName = 1,
    ETextureGameplayUse_DoNotMatchName = 2,
};

/**
 * @class cTkProceduralTexture
 */
class cTkProceduralTexture
{
  public:
    enum
    {
        ClassNameHash = 0x75816D38B6B42FE4,
    };

    union
    {
        struct
        {
            TkID<256> mName;
            cTkPaletteTexture Palette;
            float mfProbability;
            eTextureGameplayUse TextureGameplayUse;
            bool mbOverrideAverageColour;
            cTkColour mAverageColour;
            cTkFixedString<128,char> macDiffuse;
            cTkFixedString<128,char> macNormal;
            cTkFixedString<128,char> macMask;
        };
    };
};

SKYSCRAPER_END
