/**
 * @file tkimguisettings.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @class cTkImGuiSettings
 */
class cTkImGuiSettings : cTkMetaData::Registrar<cTkImGuiSettings>, cTkMetaDataXML::Registrar<cTkImGuiSettings>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x20F7F01AF38D19B2,
    };
    enum
    {
        mu64TemplateHash = 0x8C51D7C2518C871E,
    };

    cTkColour mBackgroundColour;
    cTkColour mWindowTitleColour;
    cTkColour mActiveWindowTitleColour;
    cTkColour mWindowBackgroundColour;
    cTkColour mActiveWindowBackgroundColour;
    cTkColour mWindowHighlight;
    cTkColour mTextColour;
    cTkColour mActiveTextColour;
    cTkColour mTextShadowColour;
    cTkColour mTextDisabledColour;
    cTkColour mButtonColour;
    cTkColour mButtonHighlightColour;
    cTkColour mButtonPressedColour;
    cTkColour mEditBoxColour;
    cTkColour mEditBoxActiveColour;
    cTkColour mEditBoxSelectedColour;
    cTkColour mTaskBarColour;
    cTkColour mTaskBarShadow;
    cTkColour mCloseButtonColour;
    cTkColour mCloseButtonHighlightColour;
    cTkColour mCloseButtonClickColour;
    cTkColour mMinimiseButtonColour;
    cTkColour mMinimiseButtonHighlightColour;
    cTkColour mMinimiseButtonClickColour;
    float mfScrollSpeed;
    float mfAltPlacementDistanceScrollSpeed;
};

SKYSCRAPER_END
