/**
 * @file gcexpeditioninterventioneventdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <reality/gcexpeditioncategory.meta.h>
#include <reality/gcnumberedtextlist.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcExpeditionInterventionEventData
 */
class cGcExpeditionInterventionEventData : cTkMetaData::Registrar<cGcExpeditionInterventionEventData>, cTkMetaDataXML::Registrar<cGcExpeditionInterventionEventData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x1920DA0CB7B61986,
    };
    enum
    {
        mu64TemplateHash = 0x243622A7FB6C6BCB,
    };

    TkID<256> mID;
    int miSelectionWeight;
    cGcExpeditionCategory ExpeditionCategory;
    cGcNumberedTextList InteractionID;
    cTkFixedString<32,char> macSuccessLogEntry;
    cTkFixedString<32,char> macAvoidanceLogEntry;
    cTkFixedString<32,char> macFailureLogEntry;
    TkID<128> mSuccessReward;
    TkID<128> mFailureReward;
    int miFailureDamageChance;
};

SKYSCRAPER_END
