/**
 * @file gcbiomedata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/solarsystem/planet/gcminingsubstancedata.meta.h>
#include <simulation/solarsystem/planet/gcplanetwaterdata.meta.h>
#include <simulation/environment/gcexternalobjectlistoptions.meta.h>
#include <simulation/solarsystem/planet/gcweatherweightings.meta.h>
#include <simulation/solarsystem/planet/gcbiomecloudsettings.meta.h>
#include <simulation/solarsystem/planet/gcterraincontrols.meta.h>
#include <simulation/solarsystem/planet/gcscreenfilteroption.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcBiomeData
 */
class cGcBiomeData
{
  public:
    enum
    {
        ClassNameHash = 0x2FD5560612237D4D,
    };

    inline cGcBiomeData() {}
    cGcBiomeData* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            cTkFixedString<128,char> macTextureFile;
            cTkFixedString<128,char> macOverlayFile;
            cTkFixedString<128,char> macTileTypesFile;
            cTkFixedString<128,char> macColourPaletteFile;
            cTkFixedString<128,char> macLegacyColourPaletteFile;
            cGcMiningSubstanceData MiningSubstance1;
            cGcMiningSubstanceData MiningSubstance2;
            cGcMiningSubstanceData MiningSubstance3;
            float mfFuelMultiplier;
            cGcPlanetWaterData Water;
            cTkDynamicArray<cGcExternalObjectListOptions> maExternalObjectLists;
            cTkFixedArray<cGcWeatherWeightings, 4> maWeatherOptions;
            cTkVector2 mWeatherChangeTime;
            cGcBiomeCloudSettings CloudSettings;
            cGcTerrainControls Terrain;
            cTkDynamicArray<cGcScreenFilterOption> maFilterOptions;
            TkID<256> mFloraLifeLocID;
        };
    };
};

SKYSCRAPER_END
