/**
 * @file gcplanetdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/environment/gcplanetlife.meta.h>
#include <simulation/solarsystem/planet/gcplanethazarddata.meta.h>
#include <simulation/environment/gcbuildingdensitylevels.meta.h>
#include <simulation/solarsystem/planet/gcplanetdataresourcehint.meta.h>
#include <simulation/solarsystem/planet/gcplanetcolourdata.meta.h>
#include <simulation/solarsystem/planet/gcplanetweatherdata.meta.h>
#include <simulation/environment/gcplanetcloudproperties.meta.h>
#include <simulation/solarsystem/planet/gcplanetwaterdata.meta.h>
#include <toolkit/voxel/generator/tkvoxelgeneratordata.meta.h>
#include <simulation/environment/gcenvironmentspawndata.meta.h>
#include <reality/gcalienrace.meta.h>
#include <simulation/environment/gcplanetbuildingdata.meta.h>
#include <simulation/solarsystem/planet/gcplanetgenerationintermediatedata.meta.h>
#include <simulation/solarsystem/planet/gcplanetinfo.meta.h>
#include <simulation/solarsystem/planet/gcplanetsentineldata.meta.h>
#include <simulation/solarsystem/planet/gcplanetringdata.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eResourceLevel
 */
enum eResourceLevel : uint32_t
{
    EResourceLevel_Low = 0,
    EResourceLevel_High = 1,
};

/**
 * @class cGcPlanetData
 */
class cGcPlanetData : cTkMetaData::Registrar<cGcPlanetData>, cTkMetaDataXML::Registrar<cGcPlanetData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x25EDFA0EC4C3AF0A,
    };
    enum
    {
        mu64TemplateHash = 0x2DC122FA5D947C91,
    };

    cTkFixedString<128,char> macName;
    cGcPlanetLife Life;
    cGcPlanetLife CreatureLife;
    cGcPlanetHazardData Hazard;
    eResourceLevel ResourceLevel;
    cGcBuildingDensityLevels BuildingLevel;
    TkID<128> mCommonSubstanceID;
    TkID<128> mUncommonSubstanceID;
    TkID<128> mRareSubstanceID;
    cTkDynamicArray<cGcPlanetDataResourceHint> maExtraResourceHints;
    cGcPlanetColourData Colours;
    cTkFixedArray<cTkColour, 23> maTileColours;
    cGcPlanetWeatherData Weather;
    cGcPlanetCloudProperties Clouds;
    cGcPlanetWaterData Water;
    cTkFixedString<128,char> macTerrainFile;
    cTkVoxelGeneratorData Terrain;
    int miTileTypeSet;
    cTkDynamicArray<int> maTileTypeIndices;
    cGcEnvironmentSpawnData SpawnData;
    cGcAlienRace InhabitingRace;
    cGcPlanetBuildingData BuildingData;
    cGcPlanetGenerationIntermediateData GenerationData;
    cTkVector2 mSentinelTimer;
    cTkVector2 mFlybyTimer;
    cGcPlanetInfo PlanetInfo;
    cGcPlanetSentinelData SentinelData;
    cGcPlanetRingData Rings;
    bool mbInEmptySystem;
    bool mbInAbandonedSystem;
    float mfFuelMultiplier;
};

SKYSCRAPER_END
