/**
 * @file gcnguilayoutdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <graphics/ngui/metadata/gcvroverride_layout.meta.h>
#include <graphics/ngui/metadata/gcaccessibleoverride_layout.meta.h>
#include <toolkit/ngui/tknguialignment.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcNGuiLayoutData
 */
class cGcNGuiLayoutData : cTkMetaData::Registrar<cGcNGuiLayoutData>, cTkMetaDataXML::Registrar<cGcNGuiLayoutData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xCEE71E03D7326B71,
    };
    enum
    {
        mu64TemplateHash = 0x6BF5030552548903,
    };

    cTkDynamicArray<cGcVROverride_Layout> maVROverrides;
    cTkDynamicArray<cGcAccessibleOverride_Layout> maAccessibleOverrides;
    float mfPositionX;
    float mfPositionY;
    float mfWidth;
    float mfHeight;
    float mfConstrainAspect;
    float mfMaxWidth;
    cTkNGuiAlignment Align;
    bool mbWidthPercentage;
    bool mbHeightPercentage;
    bool mbConstrainProportions;
    bool mbForceAspect;
    bool mbAnchor;
    bool mbAnchorPercent;
    bool mbSameLine;
    bool mbSlowCursorOnHover;
};

SKYSCRAPER_END
