/**
 * @file tkuserserviceauthprovider.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eAuthProvider
 */
enum eAuthProvider : uint32_t
{
    EAuthProvider_Null = 0,
    EAuthProvider_PSN = 1,
    EAuthProvider_Steam = 2,
    EAuthProvider_Galaxy = 3,
    EAuthProvider_Xbox = 4,
    EAuthProvider_WeGame = 5,
    EAuthProvider_NSO = 6,
};

/**
 * @class cTkUserServiceAuthProvider
 */
class cTkUserServiceAuthProvider
{
  public:
    enum
    {
        ClassNameHash = 0x91EF3068AEC32FB7,
    };

    inline cTkUserServiceAuthProvider() {}
    cTkUserServiceAuthProvider* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            eAuthProvider AuthProvider;
        };
    };
};

SKYSCRAPER_END
