/**
 * @file gcalienpuzzleentry.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <reality/gcalienrace.meta.h>
#include <simulation/components/gameplay/gcinteractiontype.meta.h>
#include <reality/gcalienpuzzlecategory.meta.h>
#include <reality/gcalienpuzzleoption.meta.h>
#include <reality/gcalienmood.meta.h>
#include <simulation/ecosystem/npcs/gcnpcproptype.meta.h>
#include <reality/gcpuzzletextflow.meta.h>
#include <audio/gcaudiowwiseevents.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eAdditionalOptions
 */
enum eAdditionalOptions : uint32_t
{
    EAdditionalOptions_None = 0,
    EAdditionalOptions_LearnWord = 1,
    EAdditionalOptions_SayWord = 2,
};

/**
 * @enum ePersistancyBufferOverride
 */
enum ePersistancyBufferOverride : uint32_t
{
    EPersistancyBufferOverride_None = 0,
    EPersistancyBufferOverride_AlwaysPersonal = 1,
    EPersistancyBufferOverride_AlwaysFireteam = 2,
};

/**
 * @class cGcAlienPuzzleEntry
 */
class cGcAlienPuzzleEntry : cTkMetaData::Registrar<cGcAlienPuzzleEntry>, cTkMetaDataXML::Registrar<cGcAlienPuzzleEntry>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xDE1F17CE7E01A8C2,
    };
    enum
    {
        mu64TemplateHash = 0x7922B45DF52C43C3,
    };

    int miProgressionIndex;
    int miMinProgressionForSelection;
    TkID<256> mId;
    cGcAlienRace Race;
    cGcInteractionType Type;
    cGcAlienPuzzleCategory Category;
    eAdditionalOptions AdditionalOptions;
    TkID<256> mTitle;
    TkID<256> mText;
    TkID<256> mTextAlien;
    bool mbTranslateAlienText;
    bool mbTranslationBrackets;
    bool mbProgressiveDialogue;
    TkID<256> mRequiresScanEvent;
    cTkDynamicArray<cGcAlienPuzzleOption> maOptions;
    cTkDynamicArray<TkID<256>> maAdditionalText;
    cTkDynamicArray<TkID<256>> maAdditionalTextAlien;
    cGcAlienMood Mood;
    cGcNPCPropType Prop;
    cTkDynamicArray<cGcPuzzleTextFlow> maAdvancedInteractionFlow;
    ePersistancyBufferOverride PersistancyBufferOverride;
    int miCustomFreighterTextIndex;
    bool mbRadialInteraction;
    cGcAudioWwiseEvents NextStageAudioEventOverride;
};

SKYSCRAPER_END
