/**
 * @file gcconsumableitem.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <audio/gcaudiowwiseevents.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcConsumableItem
 */
class cGcConsumableItem : cTkMetaData::Registrar<cGcConsumableItem>, cTkMetaDataXML::Registrar<cGcConsumableItem>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xDA5F4DFE0527A693,
    };
    enum
    {
        mu64TemplateHash = 0x404B0424B3A13ADA,
    };

    TkID<128> mID;
    TkID<128> mRewardID;
    TkID<128> mTutorialRewardID;
    cTkFixedString<64,char> macButtonLocID;
    cTkFixedString<64,char> macButtonSubLocID;
    bool mbCloseInventoryWhenUsed;
    cGcAudioWwiseEvents AudioEventOnOpen;
    cTkFixedString<64,char> macRewardFailedLocID;
    bool mbDestroyItemWhenConsumed;
    bool mbAddCommunityTierClassIcon;
    bool mbSuppressResourceMessage;
    TkID<256> mCustomOSD;
};

SKYSCRAPER_END
