/**
 * @file gcproceduralproductcategory.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eProceduralProductCategory
 */
enum eProceduralProductCategory : uint32_t
{
    EProceduralProductCategory_Loot = 0,
    EProceduralProductCategory_Document = 1,
    EProceduralProductCategory_BioSample = 2,
    EProceduralProductCategory_Fossil = 3,
    EProceduralProductCategory_Plant = 4,
    EProceduralProductCategory_Tool = 5,
    EProceduralProductCategory_Farm = 6,
    EProceduralProductCategory_SeaLoot = 7,
    EProceduralProductCategory_SeaHorror = 8,
    EProceduralProductCategory_Salvage = 9,
    EProceduralProductCategory_Bones = 10,
    EProceduralProductCategory_SpaceHorror = 11,
    EProceduralProductCategory_SpaceBones = 12,
    EProceduralProductCategory_FreighterPassword = 13,
    EProceduralProductCategory_FreighterCaptLog = 14,
    EProceduralProductCategory_FreighterCrewList = 15,
    EProceduralProductCategory_FreighterTechHyp = 16,
    EProceduralProductCategory_FreighterTechSpeed = 17,
    EProceduralProductCategory_FreighterTechFuel = 18,
    EProceduralProductCategory_FreighterTechTrade = 19,
    EProceduralProductCategory_FreighterTechCombat = 20,
    EProceduralProductCategory_FreighterTechMine = 21,
    EProceduralProductCategory_FreighterTechExp = 22,
    EProceduralProductCategory_DismantleBio = 23,
    EProceduralProductCategory_DismantleTech = 24,
    EProceduralProductCategory_DismantleData = 25,
};

/**
 * @class cGcProceduralProductCategory
 */
class cGcProceduralProductCategory
{
  public:
    enum
    {
        ClassNameHash = 0xE70B813560D9BFCE,
    };

    union
    {
        struct
        {
            eProceduralProductCategory ProceduralProductCategory;
        };
    };
};

SKYSCRAPER_END
