/**
 * @file gcrewardcommunitycontribution.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <atlas/gcatlassendsubmitcontribution.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eSubmitType
 */
enum eSubmitType : uint32_t
{
    ESubmitType_Value = 0,
    ESubmitType_Stat = 1,
    ESubmitType_StatsDiff = 2,
};

/**
 * @class cGcRewardCommunityContribution
 */
class cGcRewardCommunityContribution
{
  public:
    enum
    {
        ClassNameHash = 0xCE090483FC7B2C67,
    };

    inline cGcRewardCommunityContribution() {}
    cGcRewardCommunityContribution* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            cGcAtlasSendSubmitContribution Contribution;
            eSubmitType SubmitType;
            TkID<128> mStat;
            TkID<128> mOtherStat;
        };
    };
};

SKYSCRAPER_END
