/**
 * @file gcrealitysubstancecategory.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eSubstanceCategory
 */
enum eSubstanceCategory : uint32_t
{
    ESubstanceCategory_Fuel = 0,
    ESubstanceCategory_Metal = 1,
    ESubstanceCategory_Catalyst = 2,
    ESubstanceCategory_Stellar = 3,
    ESubstanceCategory_Flora = 4,
    ESubstanceCategory_Earth = 5,
    ESubstanceCategory_Exotic = 6,
    ESubstanceCategory_Special = 7,
    ESubstanceCategory_BuildingPart = 8,
};

/**
 * @class cGcRealitySubstanceCategory
 */
class cGcRealitySubstanceCategory : cTkMetaData::Registrar<cGcRealitySubstanceCategory>, cTkMetaDataXML::Registrar<cGcRealitySubstanceCategory>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x13D76408C6BF207D,
    };
    enum
    {
        mu64TemplateHash = 0x6B88061EEAA9975A,
    };

    eSubstanceCategory SubstanceCategory;
};

SKYSCRAPER_END
