/**
 * @file gcrewardsignalscan.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eSignalScanType
 */
enum eSignalScanType : uint32_t
{
    ESignalScanType_None = 0,
    ESignalScanType_DropPod = 1,
    ESignalScanType_Shelter = 2,
    ESignalScanType_Search = 3,
    ESignalScanType_Relic = 4,
    ESignalScanType_Industrial = 5,
    ESignalScanType_Alien = 6,
    ESignalScanType_CrashedFreighter = 7,
};

/**
 * @class cGcRewardSignalScan
 */
class cGcRewardSignalScan
{
  public:
    enum
    {
        ClassNameHash = 0xEDA5BCF252E3B6EF,
    };

    inline cGcRewardSignalScan() {}
    cGcRewardSignalScan* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            eSignalScanType SignalScanType;
        };
    };
};

SKYSCRAPER_END
