/**
 * @file gcrealityicontable.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <toolkit/tktextureresource.meta.h>
#include <reality/gcplanetresourceiconlookup.meta.h>
#include <reality/gcrealityicon.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcRealityIconTable
 */
class cGcRealityIconTable
{
  public:
    enum
    {
        ClassNameHash = 0x2A28407EECDFA4CC,
    };

    inline cGcRealityIconTable() {}
    cGcRealityIconTable* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            cTkFixedArray<cTkTextureResource, 6> maHazardIcons;
            cTkFixedArray<cTkTextureResource, 6> maHazardIconsHUD;
            cTkFixedArray<cTkTextureResource, 9> maSubstanceCategoryIcons;
            cTkFixedArray<cTkTextureResource, 9> maProductCategoryIcons;
            cTkFixedArray<cTkTextureResource, 9> maMissionFactionIcons;
            cTkFixedArray<cTkTextureResource, 17> maBinocularDiscoveryIcons;
            cTkFixedArray<cTkTextureResource, 7> maDiscoveryPageTradingIcons;
            cTkFixedArray<cTkTextureResource, 4> maDiscoveryPageConflictIcons;
            cTkFixedArray<cTkTextureResource, 8> maDiscoveryPageRaceIcons;
            cTkTextureResource DiscoveryPageTradingUnknown;
            cTkTextureResource DiscoveryPageConflictUnknown;
            cTkTextureResource DiscoveryPageRaceUnknown;
            cTkDynamicArray<cGcPlanetResourceIconLookup> maTerrainIconLookups;
            cTkDynamicArray<cGcPlanetResourceIconLookup> maPlanetResourceIconLookups;
            cTkDynamicArray<cTkTextureResource> maRepairTechIcons;
            cTkFixedArray<cTkTextureResource, 86> maGameIcons;
            cTkDynamicArray<cGcRealityIcon> maMissionDetailIcons;
            cTkFixedArray<cTkTextureResource, 7> maDifficultyPresetIcons;
            cTkFixedArray<cTkTextureResource, 4> maDifficultyUIOptionIcons;
            cTkFixedArray<cTkTextureResource, 5> maOptionsUIHeaderIcons;
            cTkFixedArray<cTkTextureResource, 5> maInventoryFilterIcons;
        };
    };
};

SKYSCRAPER_END
