/**
 * @file gcsettlementjudgementdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <gameplay/gcsettlementjudgementtype.meta.h>
#include <reality/gcsettlementjudgementoption.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eNPCs
 */
enum eNPCs : uint32_t
{
    ENPCs_None = 0,
    ENPCs_One = 1,
    ENPCs_Two = 2,
};

/**
 * @class cGcSettlementJudgementData
 */
class cGcSettlementJudgementData : cTkMetaData::Registrar<cGcSettlementJudgementData>, cTkMetaDataXML::Registrar<cGcSettlementJudgementData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x601CD433A66F7318,
    };
    enum
    {
        mu64TemplateHash = 0xDED5B44D3B310AC9,
    };

    cGcSettlementJudgementType JudgementType;
    float mfWeighting;
    TkID<256> mHeaderOverride;
    TkID<256> mTitle;
    TkID<256> mNPCTitle;
    TkID<256> mQuestionText;
    TkID<256> mDilemmaText;
    bool mbUseResearchLoc;
    bool mbUseAltResearchLoc;
    cGcSettlementJudgementOption Option1;
    cGcSettlementJudgementOption Option2;
    TkID<128> mNPC1CustomId;
    TkID<128> mNPC2CustomId;
    TkID<256> mNPC1CustomName;
    TkID<256> mNPC2CustomName;
    TkID<128> mNPC1HoloEffect;
    TkID<128> mNPC2HoloEffect;
    eNPCs NPCs;
};

SKYSCRAPER_END
