/**
 * @file gcunlockableitemtreegroups.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eUnlockableItemTree
 */
enum eUnlockableItemTree : uint32_t
{
    EUnlockableItemTree_Test = 0,
    EUnlockableItemTree_BasicBaseParts = 1,
    EUnlockableItemTree_BasicTechParts = 2,
    EUnlockableItemTree_BaseParts = 3,
    EUnlockableItemTree_SpecialBaseParts = 4,
    EUnlockableItemTree_SuitTech = 5,
    EUnlockableItemTree_ShipTech = 6,
    EUnlockableItemTree_WeapTech = 7,
    EUnlockableItemTree_ExocraftTech = 8,
    EUnlockableItemTree_CraftProducts = 9,
    EUnlockableItemTree_FreighterTech = 10,
    EUnlockableItemTree_S9BaseParts = 11,
    EUnlockableItemTree_S9ExoTech = 12,
    EUnlockableItemTree_S9ShipTech = 13,
};

/**
 * @class cGcUnlockableItemTreeGroups
 */
class cGcUnlockableItemTreeGroups
{
  public:
    enum
    {
        ClassNameHash = 0x8F55B25E91A470A9,
    };

    inline cGcUnlockableItemTreeGroups() {}
    cGcUnlockableItemTreeGroups* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            eUnlockableItemTree UnlockableItemTree;
        };
    };
};

SKYSCRAPER_END
