/**
 * @file gcgeneratorunitcomponentdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/components/gameplay/gcmaintenancecomponentdata.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eGeneratorUnitType
 */
enum eGeneratorUnitType : uint32_t
{
    EGeneratorUnitType_MiningUnit = 0,
    EGeneratorUnitType_GasHarvester = 1,
    EGeneratorUnitType_SystemHoover = 2,
};

/**
 * @class cGcGeneratorUnitComponentData
 */
class cGcGeneratorUnitComponentData : cTkMetaData::Registrar<cGcGeneratorUnitComponentData>, cTkMetaDataXML::Registrar<cGcGeneratorUnitComponentData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xE7D049A3A9D077A8,
    };
    enum
    {
        mu64TemplateHash = 0xFB38EAEFCC344295,
    };

    eGeneratorUnitType GeneratorUnitType;
    int miResourceMaintenanceSlotOverride;
    cTkFixedArray<TkID<128>, 16> maBiomeGasRewards;
    cGcMaintenanceComponentData MaintenanceData;
};

SKYSCRAPER_END
