/**
 * @file gcscannablecomponentdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <graphics/hud/gcscannericontypes.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eScannableType
 */
enum eScannableType : uint32_t
{
    EScannableType_Binoculars = 0,
    EScannableType_BinocularsHotspots = 1,
    EScannableType_Scanner = 2,
    EScannableType_Marker = 3,
    EScannableType_None = 4,
};

/**
 * @class cGcScannableComponentData
 */
class cGcScannableComponentData
{
  public:
    enum
    {
        ClassNameHash = 0x74BA808E86F0EC01,
    };

    inline cGcScannableComponentData() {}
    cGcScannableComponentData* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            float mfScanRange;
            cTkFixedString<32,char> macScanName;
            float mfScanTime;
            float mfCompassRangeMultiplier;
            float mfAlwaysShowRange;
            bool mbCanTagIcon;
            bool mbClearTagOnArrival;
            bool mbDisableIfBuildingPart;
            bool mbDisableIfInBase;
            bool mbUseModelNode;
            cGcScannerIconTypes Icon;
            eScannableType ScannableType;
            bool mbIsPlacedMarker;
            bool mbShowInFreighterBranchRoom;
            bool mbTellPlayerIfFreighterObjectUsed;
            TkID<256> mFreighterObjectAlreadyUsedLocID;
            bool mbAllowedToMerge;
            bool mbMarkerActiveWithNodeInactive;
            TkID<128> mMissionSurveyId;
            float mfMinDisplayDistanceOverride;
        };
    };
};

SKYSCRAPER_END
