/**
 * @file gcplayerhazarddata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <toolkit/animation/tkcurvetype.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcPlayerHazardData
 */
class cGcPlayerHazardData : cTkMetaData::Registrar<cGcPlayerHazardData>, cTkMetaDataXML::Registrar<cGcPlayerHazardData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x18642126695741B5,
    };
    enum
    {
        mu64TemplateHash = 0x362521D640B1A7DE,
    };

    float mfProtectionInitialTime;
    cTkVector2 mProtectionTime;
    cTkVector2 mDamageRate;
    cTkVector2 mWoundRate;
    float mfRechargeInitialTime;
    float mfRechargeTime;
    TkID<128> mDamage;
    bool mbIncreases;
    cTkCurveType DisplayCurve;
    float mfTriggerValue;
    float mfCapValue;
    float mfCriticalValue;
    float mfOutputMultiplier;
    float mfOutputMinAddition;
    float mfOutputMaxAddition;
};

SKYSCRAPER_END
