/**
 * @file gcscandata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eScanType
 */
enum eScanType : uint32_t
{
    EScanType_Tool = 0,
    EScanType_Beacon = 1,
    EScanType_RadioTower = 2,
    EScanType_Observatory = 3,
    EScanType_DistressSignal = 4,
    EScanType_Waypoint = 5,
    EScanType_Ship = 6,
    EScanType_DebugPlanet = 7,
    EScanType_DebugSpace = 8,
    EScanType_VisualOnly = 9,
    EScanType_VisualOnlyAerial = 10,
};

/**
 * @class cGcScanData
 */
class cGcScanData : cTkMetaData::Registrar<cGcScanData>, cTkMetaDataXML::Registrar<cGcScanData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x8531B20A02DD0931,
    };
    enum
    {
        mu64TemplateHash = 0x10D41904DB6F3321,
    };

    eScanType ScanType;
    float mfPulseRange;
    float mfPulseTime;
    bool mbPlayAudioOnMarkers;
    float mfChargeTime;
};

SKYSCRAPER_END
