/**
 * @file gcnpcinteractiveobjectstate.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/ecosystem/npcs/gcnpcproptype.meta.h>
#include <simulation/ecosystem/npcs/gcnpcseatedposture.meta.h>
#include <simulation/npcs/gcnpcprobabilityanimationdata.meta.h>
#include <simulation/npcs/gcnpcinteractiveobjectstatetransition.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcNPCInteractiveObjectState
 */
class cGcNPCInteractiveObjectState
{
  public:
    enum
    {
        ClassNameHash = 0x8D18F9F6D2A592B3,
    };

    union
    {
        struct
        {
            TkID<128> mName;
            bool mbFaceSpawnDir;
            bool mbFaceNodeDir;
            bool mbFaceInvNodeDir;
            bool mbLookAtModel;
            cTkFixedString<64,char> macLookAtNode;
            bool mbFaceLookAt;
            bool mbMaintainLookAt;
            bool mbPlayIdles;
            bool mbCanConverse;
            cGcNPCPropType Prop;
            cGcNPCSeatedPosture SeatedPosture;
            float mfBlendTime;
            float mfEarlyOutTime;
            cTkDynamicArray<cGcNPCProbabilityAnimationData> maAnimations;
            float mfSpineAdjustAmount;
            int miMinAnims;
            int miMaxAnims;
            float mfMinTime;
            float mfMaxTime;
            cTkDynamicArray<cGcNPCInteractiveObjectStateTransition> maTransitions;
        };
    };
};

SKYSCRAPER_END
