/**
 * @file gccreatureiktype.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eCreatureIkType
 */
enum eCreatureIkType : uint32_t
{
    ECreatureIkType_Foot = 0,
    ECreatureIkType_Hinge_X = 1,
    ECreatureIkType_Hinge_Y = 2,
    ECreatureIkType_Hinge_Z = 3,
    ECreatureIkType_Locked = 4,
    ECreatureIkType_Head = 5,
    ECreatureIkType_Toe = 6,
    ECreatureIkType_SpaceshipFoot = 7,
    ECreatureIkType_SpaceshipToe = 8,
};

/**
 * @class cGcCreatureIkType
 */
class cGcCreatureIkType : cTkMetaData::Registrar<cGcCreatureIkType>, cTkMetaDataXML::Registrar<cGcCreatureIkType>
{
  public:
    enum
    {
        mu64ClassNameHash = 0x1A5C8AEE15BC00C7,
    };
    enum
    {
        mu64TemplateHash = 0x42748B3F25F8C43A,
    };

    eCreatureIkType CreatureIkType;
};

SKYSCRAPER_END
