/**
 * @file gcenvironmentproperties.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcEnvironmentProperties
 */
class cGcEnvironmentProperties
{
  public:
    enum
    {
        ClassNameHash = 0xB125AED843BB9164,
    };

    inline cGcEnvironmentProperties() {}
    cGcEnvironmentProperties* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            float mfFlightFogHeight;
            float mfFlightFogBlend;
            float mfCloudHeightMin;
            float mfCloudHeightMax;
            float mfHeavyAirHeightMin;
            float mfHeavyAirHeightMax;
            float mfPlanetObjectSwitch;
            float mfPlanetLodSwitch0;
            float mfPlanetLodSwitch0Elevation;
            float mfPlanetLodSwitch1;
            float mfPlanetLodSwitch2;
            float mfPlanetLodSwitch3;
            float mfAsteroidFadeHeightMin;
            float mfAsteroidFadeHeightMax;
            cTkFixedArray<float, 4> maSkyHeight;
            float mfSkyAtmosphereHeight;
            float mfHorizonBlendHeight;
            float mfHorizonBlendLength;
            float mfSkyColourHeight;
            float mfSkyColourBlendLength;
            float mfSkyPositionHeight;
            float mfSkyPositionBlendLength;
            float mfSolarSystemLUTHeight;
            float mfSolarSystemLUTBlendLength;
            float mfAtmosphereStartHeight;
            float mfAtmosphereEndHeight;
            float mfStratosphereHeight;
        };
    };
};

SKYSCRAPER_END
