/**
 * @file gcobjectdefinitiondata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eObjectRenderType
 */
enum eObjectRenderType : uint32_t
{
    EObjectRenderType_Instanced = 0,
    EObjectRenderType_Single = 1,
};

/**
 * @enum eSizeClass
 */
enum eSizeClass : uint32_t
{
    ESizeClass_Tiny = 0,
    ESizeClass_Small = 1,
    ESizeClass_Medium = 2,
    ESizeClass_Large = 3,
    ESizeClass_Massive = 4,
};

/**
 * @enum eObjectCoverageType
 */
enum eObjectCoverageType : uint32_t
{
    EObjectCoverageType_Blanket = 0,
    EObjectCoverageType_Cluster = 1,
    EObjectCoverageType_Solo = 2,
};

/**
 * @enum eLifeType
 */
enum eLifeType : uint32_t
{
    ELifeType_Rock = 0,
    ELifeType_DryPlant = 1,
    ELifeType_LushPlant = 2,
    ELifeType_Artificial = 3,
};

/**
 * @enum eLocationType
 */
enum eLocationType : uint32_t
{
    ELocationType_AboveGround = 0,
    ELocationType_UnderGround = 1,
    ELocationType_WaterSurface = 2,
    ELocationType_UnderWater = 3,
};

/**
 * @enum eObjectAlignment
 */
enum eObjectAlignment : uint32_t
{
    EObjectAlignment_Upright = 0,
    EObjectAlignment_SlightOffsetFromUpright = 1,
    EObjectAlignment_LargeOffsetFromUpright = 2,
    EObjectAlignment_ToNormal = 3,
    EObjectAlignment_SlightOffsetFromNormal = 4,
    EObjectAlignment_LargeOffsetFromNormal = 5,
};

/**
 * @class cGcObjectDefinitionData
 */
class cGcObjectDefinitionData
{
  public:
    enum
    {
        ClassNameHash = 0xF6BC04E88CDBB164,
    };

    inline cGcObjectDefinitionData() {}
    cGcObjectDefinitionData* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            cTkFixedString<128,char> macFilename;
            eObjectRenderType ObjectRenderType;
            bool mbAutoCollision;
            bool mbMatchGroundColour;
            eSizeClass SizeClass;
            eObjectCoverageType ObjectCoverageType;
            eLifeType LifeType;
            eLocationType LocationType;
            eObjectAlignment ObjectAlignment;
        };
    };
};

SKYSCRAPER_END
