/**
 * @file tknoisevoxeltypeenum.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eNoiseVoxelType
 */
enum eNoiseVoxelType : uint32_t
{
    ENoiseVoxelType_Base = 0,
    ENoiseVoxelType_Rock = 1,
    ENoiseVoxelType_Mountain = 2,
    ENoiseVoxelType_Sand = 3,
    ENoiseVoxelType_Cave = 4,
    ENoiseVoxelType_Substance_1 = 5,
    ENoiseVoxelType_Substance_2 = 6,
    ENoiseVoxelType_Substance_3 = 7,
    ENoiseVoxelType_RandomRock = 8,
    ENoiseVoxelType_RandomRockOrSubstance = 9,
};

/**
 * @class cTkNoiseVoxelTypeEnum
 */
class cTkNoiseVoxelTypeEnum : cTkMetaData::Registrar<cTkNoiseVoxelTypeEnum>, cTkMetaDataXML::Registrar<cTkNoiseVoxelTypeEnum>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xA54BFECBD79D65EE,
    };
    enum
    {
        mu64TemplateHash = 0x23F660CE1EB9E712,
    };

    eNoiseVoxelType NoiseVoxelType;
};

SKYSCRAPER_END
