/**
 * @file gccustomisationcomponentdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eCustomisationDataType
 */
enum eCustomisationDataType : uint32_t
{
    ECustomisationDataType_Player = 0,
    ECustomisationDataType_Vehicle = 1,
    ECustomisationDataType_Weapon = 2,
    ECustomisationDataType_Ship_01 = 3,
    ECustomisationDataType_Ship_02 = 4,
    ECustomisationDataType_Ship_03 = 5,
    ECustomisationDataType_Ship_04 = 6,
    ECustomisationDataType_Ship_05 = 7,
    ECustomisationDataType_Ship_06 = 8,
    ECustomisationDataType_Vehicle_Bike = 9,
    ECustomisationDataType_Vehicle_Truck = 10,
    ECustomisationDataType_Vehicle_WheeledBike = 11,
    ECustomisationDataType_Vehicle_Hovercraft = 12,
    ECustomisationDataType_Vehicle_Submarine = 13,
    ECustomisationDataType_Vehicle_Mech = 14,
    ECustomisationDataType_Freighter = 15,
    ECustomisationDataType_Pet = 16,
    ECustomisationDataType_Ship_07 = 17,
    ECustomisationDataType_Ship_08 = 18,
    ECustomisationDataType_Ship_09 = 19,
    ECustomisationDataType_Ship_10 = 20,
    ECustomisationDataType_Ship_11 = 21,
    ECustomisationDataType_Ship_12 = 22,
};

/**
 * @class cGcCustomisationComponentData
 */
class cGcCustomisationComponentData
{
  public:
    enum
    {
        ClassNameHash = 0x52B0589631E97AC5,
    };

    union
    {
        struct
        {
            eCustomisationDataType CustomisationDataType;
        };
    };
};

SKYSCRAPER_END
