/**
 * @file gccustomisationbackpackdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcCustomisationBackpackData
 */
class cGcCustomisationBackpackData : cTkMetaData::Registrar<cGcCustomisationBackpackData>, cTkMetaDataXML::Registrar<cGcCustomisationBackpackData>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xF9391B96F83DAF40,
    };
    enum
    {
        mu64TemplateHash = 0xB44E6EA2FA256B5F,
    };

    cTkFixedString<32,char> macNodeName;
    cTkVector3 mActiveJetOffset;
};

SKYSCRAPER_END
