/**
 * @file gcwfcface.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eTransform
 */
enum eTransform : uint32_t
{
    ETransform_None = 0,
    ETransform_Rotated90 = 1,
    ETransform_Rotated180 = 2,
    ETransform_Rotated270 = 3,
    ETransform_FlippedHorizontally = 4,
};

/**
 * @class cGcWFCFace
 */
class cGcWFCFace : cTkMetaData::Registrar<cGcWFCFace>, cTkMetaDataXML::Registrar<cGcWFCFace>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xAD33210D14B166A3,
    };
    enum
    {
        mu64TemplateHash = 0x95F7AB7D4A3778A0,
    };

    cTkFixedString<32,char> macConnector;
    bool mbSymmetric;
    eTransform Transform;
    cTkDynamicArray<TkID<128>> maExcludedNeighboursR0;
    cTkDynamicArray<TkID<128>> maExcludedNeighboursR1;
    cTkDynamicArray<TkID<128>> maExcludedNeighboursR2;
    cTkDynamicArray<TkID<128>> maExcludedNeighboursR3;
    bool mbWalkable;
    bool mbIncomplete;
    bool mbIsEntrance;
    TkID<128> mName;
};

SKYSCRAPER_END
