/**
 * @file gcgamemode.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum ePresetGameMode
 */
enum ePresetGameMode : uint32_t
{
    EPresetGameMode_Unspecified = 0,
    EPresetGameMode_Normal = 1,
    EPresetGameMode_Creative = 2,
    EPresetGameMode_Survival = 3,
    EPresetGameMode_Ambient = 4,
    EPresetGameMode_Permadeath = 5,
    EPresetGameMode_Seasonal = 6,
};

/**
 * @class cGcGameMode
 */
class cGcGameMode
{
  public:
    enum
    {
        ClassNameHash = 0x2BFE76ABF5398879,
    };

    union
    {
        struct
        {
            ePresetGameMode PresetGameMode;
        };
    };
};

SKYSCRAPER_END
