/**
 * @file gcpetdata.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-15
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <simulation/solarsystem/planet/gcbiometype.meta.h>
#include <simulation/ecosystem/creatures/gccreaturetypes.meta.h>
#include <reality/gcdiscoveryowner.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcPetData
 */
class cGcPetData
{
  public:
    enum
    {
        ClassNameHash = 0x995CD6C5BC075C98,
    };

    union
    {
        struct
        {
            float mfScale;
            TkID<128> mCreatureID;
            cTkDynamicArray<TkID<256>> maDescriptors;
            cTkSeed mCreatureSeed;
            cTkSeed mCreatureSecondarySeed;
            unsigned long long mui64SpeciesSeed;
            unsigned long long mui64GenusSeed;
            TkID<256> mCustomSpeciesName;
            bool mbPredator;
            unsigned long long mui64UA;
            bool mbAllowUnmodifiedReroll;
            cTkSeed mColourBaseSeed;
            cTkSeed mBoneScaleSeed;
            bool mbHasFur;
            cGcBiomeType Biome;
            cGcCreatureTypes CreatureType;
            unsigned long long mui64BirthTime;
            unsigned long long mui64LastEggTime;
            unsigned long long mui64LastTrustIncreaseTime;
            unsigned long long mui64LastTrustDecreaseTime;
            bool mbEggModified;
            bool mbHasBeenSummoned;
            cTkFixedString<32,char> macCustomName;
            float mfTrust;
            cGcDiscoveryOwner SenderData;
            cTkFixedArray<float, 3> maTraits;
            cTkFixedArray<float, 2> maMoods;
        };
    };
};

SKYSCRAPER_END
