/**
 * @file gcplayermissionparticipanttype.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-24
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>

SKYSCRAPER_BEGIN

/**
 * @enum eParticipantType
 */
enum eParticipantType : uint32_t
{
    EParticipantType_None = 0,
    EParticipantType_MissionGiver = 1,
    EParticipantType_MissionGiverReference = 2,
    EParticipantType_Primary = 3,
    EParticipantType_Secondary1 = 4,
    EParticipantType_Secondary2 = 5,
    EParticipantType_Secondary3 = 6,
    EParticipantType_Secondary4 = 7,
    EParticipantType_Secondary5 = 8,
    EParticipantType_Secondary6 = 9,
    EParticipantType_Secondary7 = 10,
    EParticipantType_Secondary8 = 11,
    EParticipantType_Secondary9 = 12,
};

/**
 * @class cGcPlayerMissionParticipantType
 */
class cGcPlayerMissionParticipantType
{
  public:
    enum
    {
        ClassNameHash = 0x233DD65A730CE9DF,
    };

    inline cGcPlayerMissionParticipantType() {}
    cGcPlayerMissionParticipantType* Cast(cTkClassPointer* lClassPtr);

    union
    {
        struct
        {
            eParticipantType ParticipantType;
        };
    };
};

SKYSCRAPER_END
