/**
 * @file gcexperiencedebugtriggerinput.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <player/experience/gcexperiencedebugtriggeraction.meta.h>

SKYSCRAPER_BEGIN

/**
 * @enum eKeyPress
 */
enum eKeyPress : uint32_t
{
    EKeyPress_1 = 0,
    EKeyPress_2 = 1,
    EKeyPress_3 = 2,
    EKeyPress_4 = 3,
    EKeyPress_5 = 4,
    EKeyPress_6 = 5,
    EKeyPress_7 = 6,
    EKeyPress_8 = 7,
    EKeyPress_9 = 8,
    EKeyPress_PadUp = 9,
    EKeyPress_PadDown = 10,
    EKeyPress_PadLeft = 11,
    EKeyPress_PadRight = 12,
};

/**
 * @class cGcExperienceDebugTriggerInput
 */
class cGcExperienceDebugTriggerInput : cTkMetaData::Registrar<cGcExperienceDebugTriggerInput>, cTkMetaDataXML::Registrar<cGcExperienceDebugTriggerInput>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xBCDA670B36E2534,
    };
    enum
    {
        mu64TemplateHash = 0xC72994D29824460B,
    };

    eKeyPress KeyPress;
    cTkDynamicArray<cGcExperienceDebugTriggerAction> maActions;
};

SKYSCRAPER_END
