/**
 * @file gcdifficultyconfig.meta.h
 * @author VITALISED & Contributors
 * @since 2023-12-06
 * @version v101236
 * @brief This file is autogenerated metadata created by Heridium for ReNMS. You shouldn't need to modify this, see https://github.com/VITALISED/renms.
 *
 * Copyright (C) 2023  VITALISED & Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version. 
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <toolkit/data/TkMetaDataClasses.h>
#include <user/gcdifficultysettingsdata.meta.h>
#include <user/gcdifficultyoptionuigroup.meta.h>
#include <user/gcdifficultysettingcommondata.meta.h>
#include <user/gcdifficultystartwithallitemsknownoptiondata.meta.h>
#include <user/gcdifficultyinventorystacksizeoptiondata.meta.h>
#include <user/gcdifficultyfueluseoptiondata.meta.h>
#include <user/gcdifficultycurrencycostoptiondata.meta.h>
#include <user/gcitemshopavailabilitydifficultyoptiondata.meta.h>

SKYSCRAPER_BEGIN

/**
 * @class cGcDifficultyConfig
 */
class cGcDifficultyConfig : cTkMetaData::Registrar<cGcDifficultyConfig>, cTkMetaDataXML::Registrar<cGcDifficultyConfig>
{
  public:
    enum
    {
        mu64ClassNameHash = 0xA688E4255C8FED76,
    };
    enum
    {
        mu64TemplateHash = 0x24D7B6A525FF59C4,
    };

    TkID<256> mPresetLocId;
    cTkFixedArray<TkID<256>, 7> maPresetOptionLocIds;
    cTkFixedArray<cGcDifficultySettingsData, 7> maPresets;
    cGcDifficultySettingsData PermadeathMinSettings;
    cTkFixedArray<cGcDifficultyOptionUIGroup, 4> maUILayout;
    cTkFixedArray<cGcDifficultySettingCommonData, 28> maCommonSettingsData;
    int miAllSlotsUnlockedStartingSuitSlots;
    int miAllSlotsUnlockedStartingSuitTechSlots;
    int miAllSlotsUnlockedStartingWeaponSlots;
    int miAllSlotsUnlockedStartingShipSlots;
    int miAllSlotsUnlockedStartingShipTechSlots;
    cGcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownDisabledData;
    cGcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownEnabledData;
    cTkFixedArray<TkID<256>, 3> maCreatureHostilityOptionLocIds;
    cTkFixedArray<TkID<256>, 4> maDeathConsequencesOptionLocIds;
    cTkFixedArray<TkID<256>, 4> maDamageReceivedOptionLocIds;
    cTkFixedArray<float, 4> maDamageReceivedMultipliers;
    cTkFixedArray<int, 4> maDamageReceivedAIMechTechDamageHits;
    cTkFixedArray<TkID<256>, 3> maDamageGivenOptionLocIds;
    cTkFixedArray<float, 3> maDamageGivenMultipliers;
    cTkFixedArray<TkID<256>, 4> maActiveSurvivalBarsOptionLocIds;
    cTkFixedArray<TkID<256>, 3> maHazardDrainOptionLocIds;
    cTkFixedArray<float, 3> maHazardDrainMultipliers;
    cTkFixedArray<TkID<256>, 3> maEnergyDrainOptionLocIds;
    cTkFixedArray<float, 3> maEnergyDrainMultipliers;
    cTkFixedArray<TkID<256>, 3> maSubstanceCollectionOptionLocIds;
    cTkFixedArray<float, 3> maSubstanceCollectionMultipliers;
    cTkFixedArray<int, 3> maSubstanceCollectionLaserAmount;
    cTkFixedArray<TkID<256>, 3> maInventoryStackLimitsOptionLocIds;
    cTkFixedArray<cGcDifficultyInventoryStackSizeOptionData, 3> maInventoryStackLimitsOptionData;
    cTkFixedArray<TkID<256>, 4> maChargingRequirementsOptionLocIds;
    cTkFixedArray<float, 4> maChargingRequirementsMultipliers;
    cTkFixedArray<TkID<256>, 4> maFuelUseOptionLocIds;
    cTkFixedArray<cGcDifficultyFuelUseOptionData, 4> maFuelUseOptionData;
    cTkFixedArray<TkID<256>, 4> maLaunchFuelCostOptionLocIds;
    cTkFixedArray<float, 4> maLaunchFuelCostMultipliers;
    cTkFixedArray<float, 4> maShipSummoningFuelCostMultipliers;
    cTkFixedArray<TkID<256>, 4> maCurrencyCostOptionLocIds;
    cTkFixedArray<cGcDifficultyCurrencyCostOptionData, 4> maCurrencyCostOptionData;
    cTkFixedArray<TkID<256>, 3> maItemShopAvailabilityOptionLocIds;
    cTkFixedArray<cGcItemShopAvailabilityDifficultyOptionData, 3> maItemShopAvailabilityOptionData;
    cTkFixedArray<TkID<256>, 4> maScannerRechargeOptionLocIds;
    cTkFixedArray<float, 4> maScannerRechargeMultipliers;
    cTkFixedArray<TkID<256>, 4> maReputationGainOptionLocIds;
    cTkFixedArray<float, 4> maReputationGainMultipliers;
    cTkFixedArray<TkID<256>, 4> maSpaceCombatOptionLocIds;
    cTkFixedArray<float, 4> maSpaceCombatMultipliers;
    cTkFixedArray<float, 4> maSpaceCombatDifficultyMultipliers;
    cTkFixedArray<TkID<256>, 4> maGroundCombatOptionLocIds;
    cTkFixedArray<float, 4> maGroundCombatMultipliers;
    cTkFixedArray<float, 4> maSentinelTimeOutMultipliers;
    cTkFixedArray<TkID<256>, 3> maSprintingOptionLocIds;
    cTkFixedArray<float, 3> maSprintingCostMultipliers;
    cTkFixedArray<TkID<256>, 3> maBreakTechOnDamageOptionLocIds;
    cTkFixedArray<float, 3> maBreakTechOnDamageMultipliers;
};

SKYSCRAPER_END
